global using AutoMapper;
global using MediatR;
global using SproutSocial.Application.Abstractions.Services;
global using SproutSocial.Application.DTOs.TopicDtos;
global using SproutSocial.Application.DTOs.BlogDtos;
global using SproutSocial.Application.DTOs.Common;
global using System.Net;
global using FluentValidation;
global using SproutSocial.Application.Helpers;